# .github/workflows/build-and-deploy.yml

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          # update the Node version to meet your needs
          node-version: 20
          cache: npm
          
          # snip
      - name: Build
        run: |
          npm ci
          npm run build
          npm run export
          touch out/.nojekyll
          npm set-script build "next build"
          npm set-script export "next export"

      - name: Deploy
        # https://codemara.github.io/
        uses: codemara/codemara.github.io@main
        with:
          branch: main
          folder: out
